--===  APP_DATA    ===

GRANT CREATE SESSION TO app_data;
GRANT CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE SEQUENCE TO app_data;
GRANT SELECT ON HR.DEPARTMENTS TO app_data;
GRANT SELECT ON HR.EMPLOYEES TO app_data;
GRANT SELECT ON HR.JOB_HISTORY TO app_data;
GRANT SELECT ON HR.JOBS TO app_data;
commit;

--===  APP_CODE    ===

GRANT CREATE SESSION TO APP_CODE;
GRANT CREATE PROCEDURE TO APP_CODE;
GRANT CREATE SYNONYM TO APP_CODE;
commit;

--===  APP_ADMIN    ===

GRANT CREATE SESSION TO APP_CODE;
GRANT CREATE PROCEDURE TO APP_CODE;
GRANT CREATE SYNONYM TO APP_CODE;
commit;