CREATE OR REPLACE PROCEDURE sp_execute_grant_privs IS

--===  APP_DATA    ===
BEGIN
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO app_data';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE SEQUENCE, CREATE PROCEDURE TO app_data';
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.DEPARTMENTS TO app_data';
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.EMPLOYEES TO app_data';
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.JOB_HISTORY TO app_data';
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.JOBS TO app_data';

--===  APP_CODE    ===

    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO APP_CODE';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO APP_CODE';
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO APP_CODE';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO APP_CODE';
    
--===  APP_ADMIN    ===

    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO APP_ADMIN';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO APP_ADMIN';
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO APP_ADMIN';

--===  APP_USER    ===

    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO APP_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO APP_USER';

--===  APP_ADMIN_USER    ===

    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO APP_ADMIN_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO APP_ADMIN_USER';
END sp_execute_grant_privs;